site_name: Gentoo Linux Installation
site_url: https://duxsco.github.io/gentoo-installation/
repo_url: https://github.com/duxsco/gentoo-installation/
repo_name: duxsco/gentoo-installation
edit_uri: blob/main/docs/
site_description: Gentoo installation using Measured Boot, Secure Boot, Full Disk Encryption, RAID and offering a rescue system based on customised SystemRescueCD
site_author: David Sardari
remote_branch: gh-pages
remote_name: origin
theme:
  name: material
  locale: en
  use_directory_urls: true
plugins:
  - search
  - enumerate-headings
nav:
  - Introduction: index.md
  - Live-CD Environment: 02_live-cd_environment.md
  - Disk Setup: 03_disk_setup.md
  - Rescue System: 04_rescue_system.md
  - Chrooting: 05_chrooting.md
  - System Setup: 06_system_setup.md
  - Boot Setup: 07_boot_setup.md
  - Cleanup And Reboot: 08_cleanup_and_reboot.md
  - Post-Boot Configuration: 09_post_boot_configuration.md
  - Optional Steps: 10_optional_steps.md
  - Other Gentoo Linux Repos: 11_other_gentoo_linux_repos.md
