site_name: Gentoo Linux Installation
site_url: https://gentoo.duxsco.de/
repo_url: https://github.com/duxsco/gentoo-installation/
repo_name: duxsco/gentoo-installation
edit_uri: blob/main/docs/
site_description: Gentoo installation using Measured Boot, Secure Boot, Full Disk Encryption, RAID and offering a rescue system based on customised SystemRescueCD
site_author: David Sardari
remote_branch: gh-pages
remote_name: origin
theme:
  name: material
  locale: en
  use_directory_urls: true
  features:
    - navigation.instant
  font: false
  icon:
    repo: material/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
        remove_comments: true
nav:
  - 1. Introduction: index.md
  - 2. Live-CD Environment: live-cd_environment.md
  - 3. Disk Setup: disk_setup.md
  - 4. Rescue System: rescue_system.md
  - 5. Chrooting: chrooting.md
  - 6. System Setup: system_setup.md
  - 7. Cleanup And Reboot: cleanup_and_reboot.md
  - 8. Post-Boot Configuration: post-boot_configuration.md
  - 9. Virtual Server (optional): virtual_server.md
  - 10. SELinux (optional) (WIP): selinux.md
  - 11. Other Gentoo Linux repos: other_gentoo_linux_repos.md
