site_name: Gentoo Linux with Measured Boot
site_url: https://gentoo.duxsco.de/
repo_url: https://github.com/duxsco/gentoo-installation/
repo_name: duxsco/gentoo-installation
edit_uri: blob/main/docs/
site_description: Gentoo installation using Measured Boot, Secure Boot, Full Disk Encryption, RAID and offering a rescue system based on customised SystemRescueCD
site_author: David Sardari
remote_branch: gh-pages
remote_name: origin
theme:
  name: material
  locale: en
  use_directory_urls: true
  features:
    - content.code.annotate
    - navigation.footer
    - navigation.instant
  font: false
  icon:
    repo: material/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: True
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: false
      minify_css: false
      htmlmin_opts:
        remove_comments: true
nav:
  - 1. Introduction: index.md
  - 2. Live-CD Environment: live-cd_environment.md
  - 3. Disk Setup: disk_setup.md
  - 4. Rescue System: rescue_system.md
  - 5. Chrooting: chrooting.md
  - 6. Portage Setup: portage_setup.md
  - 7. Non-Root User: non-root_user.md
  - 8. Bootup Setup: bootup_setup.md
  - 9. Unified Kernel Image: unified_kernel_image.md
  - 10. SSH Server (optional): ssh_server.md
  - 11. Cleanup And Reboot: cleanup_and_reboot.md
  - 12. Post-Boot Configuration: post-boot_configuration.md
  - 13. Virtual Server (optional): virtual_server.md
  - 14. SELinux (optional): selinux.md
  - 15. Desktop Profiles (optional): desktop_profiles.md
  - 16. Other Gentoo Linux Repos: other_gentoo_linux_repos.md
